# Tensors

**Tensors are specialized data structure that are very similar to arrays and matrices. In Pytorch, we use tensors to encodde the inputs and outputs.**


Tensors are similar to NumPys ndarrays, except that tensors can run on GPUs or other hardwares accelerators.Tensors are also optimzed for automatic differentiation.

In [1]:
import torch
import numpy as np

## Initializing Tensor

### Tensors are initializes in two ways
1. Directly from data
the data types is automaticaly inferred.

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

### From a NumPy array

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### From other Tensor:

The new tensor retains the properties(shape,datatype) of the argument tensor, unless explicitly overidden.

In [4]:
x_one = torch.ones_like(x_data)

print(f"Ones Tensor:\n {x_one}\n")

x_rand= torch.rand_like(x_data,dtype = torch.float)# overrides the datatype of x_data 
 
print(f"Random Tensor: \n {x_rand}\n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.9131, 0.6141],
        [0.0441, 0.1829]])



### with random or constant values

Shape is a tuple of tensor dimensions. In the functions the determines of the output tensor.

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeroes_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor}\n")
print(f"Ones Tensor: \n{ones_tensor}\n")
print(f"Zeroes Tensor: \n{zeroes_tensor}\n")

Random Tensor: 
tensor([[0.6059, 0.4638, 0.2178],
        [0.8365, 0.5768, 0.1013]])

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeroes Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## Attributes of a Tensor

Tensor attributes describle their shape, datatype, and the device on which they are stored.

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype tensor is stored on {tensor.dtype}" )
print(f"Device tensor is stored on :{tensor.device}")

Shape of tensor:torch.Size([3, 4])
Datatype tensor is stored on torch.float32
Device tensor is stored on :cpu


### Operations on Tensors

over 1200 tensor operates , including arithmetic, linear algebra, matrix manipulation(trasposing, indexing, slicing),
sampling.

Each of these operations can be run on the CPU and Accelerator such CUDA, MTIa or XPU

By default tensors are created on the CPU. We need to explicity move tensors to the accelator 

In [7]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [8]:
# !pip uninstall torch

In [9]:
# !pip install torch

In [10]:
pip show torch

Name: torch
Version: 2.6.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: c:\users\acer\anaconda3\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision
Note: you may need to restart the kernel to use updated packages.


In [11]:
!pip install --upgrade torch torchvision torchaudio



In [12]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


### Standard numpy-like indexing and slicing

In [13]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column:{tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column:tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining tensors

You can use torch.cat to cancatenate a sequence of tensors along a given dimensions.

In [14]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)

In [15]:
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## Arithemetic operations


In [16]:
#@ this compuptes the martix multiplication between two tensors. y1,y2,y3 will have the same value 

y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [17]:
z1 = tensor*tensor
z2 =tensor.mul(tensor.T)

z3 = torch.rand_like(tensor)

torch.mul(tensor,tensor,out= z3
         )

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
## Single-element tensors if you have a one-element tensor, for
# aggregating all values of a tensor into in one value, you can  convert it to a pythobn
# numerical value using item()

In [19]:
agg = tensor.sum()
agg_item = agg.item()
print(agg,type(agg_item))

tensor(12.) <class 'float'>


### In-place operations

**Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. for example x.copy_(), x.t_() will change x.**

In [21]:
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**In-place operations save the memory, but can be problematic when computing derivates because of an immdiate loss of history. Hence,their use is discouraged.**

## Cross conversion from numpy to tensor and vice and versa.

In [24]:
n = np.ones(5)
t = torch.from_numpy(n)

In [25]:
np.add(n,1,out = n)
print(f"t:{t}")
print(f"n: {n}")

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
