# Tensors

**Tensors are specialized data structure that are very similar to arrays and matrices. In Pytorch, we use tensors to encodde the inputs and outputs.**


Tensors are similar to NumPys ndarrays, except that tensors can run on GPUs or other hardwares accelerators.Tensors are also optimzed for automatic differentiation.

In [1]:
import torch
import numpy as np

## Initializing Tensor

### Tensors are initializes in two ways
1. Directly from data

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

### From a NumPy array

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### From other Tensor:

The new tensor retains the properties(shape,datatype) of the argument tensor, unless explicitly overidden.

In [4]:
x_one = torch.ones_like(x_data)

print(f"Ones Tensor:\n {x_one}\n")

x_rand= torch.rand_like(x_data,dtype = torch.float)# overrides the datatype of x_data 
 
print(f"Random Tensor: \n {x_rand}\n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.5588, 0.2239],
        [0.0763, 0.0592]])



### with random or constant values

Shape is a tuple of tensor dimensions. In the functions the determines of the output tensor.

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeroes_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor}\n")
print(f"Ones Tensor: \n{ones_tensor}\n")
print(f"Zeroes Tensor: \n{zeroes_tensor}\n")

Random Tensor: 
tensor([[0.4025, 0.2408, 0.1665],
        [0.6840, 0.1847, 0.5507]])

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeroes Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## Attributes of a Tensor

Tensor attributes describle their shape, datatype, and the device on which they are stored.

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype tensor is stored on {tensor.dtype}" )
print(f"Device tensor is stored on :{tensor.device}")

Shape of tensor:torch.Size([3, 4])
Datatype tensor is stored on torch.float32
Device tensor is stored on :cpu


### Operations on Tensors

over 1200 tensor operates , including arithmetic, linear algebra, matrix manipulation(trasposing, indexing, slicing),
sampling.

Each of these operations can be run on the CPU and Accelerator such CUDA, MTIa or XPU

By default tensors are created on the CPU. We need to explicity move tensors to the accelator 

In [7]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [8]:
# !pip uninstall torch

In [9]:
# !pip install torch

In [10]:
pip show torch

Name: torch
Version: 2.6.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: c:\users\acer\anaconda3\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision
Note: you may need to restart the kernel to use updated packages.


In [ ]:
!pip install --upgrade torch torchvision torchaudio



In [ ]:
pip install --upgrade pip